baseurl = "https://monoscope.tech/"
title = "monoscope: Find and fix issues before customers notice!"
theme = "apitoolkit"
languageCode = 'en-us'
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
summarylength = 30


[Params]
mainSections = ["blog"]
intro = true
headline = "monoscope"
description = "Monitoring and Observability Platform"
github = "https://github.com/monoscope-tech"
twitter = "@apitoolkithq"
email = "hello@monoscope.tech"
opengraph = true
shareTwitter = true
dateFormat = "Mon, Jan 2, 2006"
ogimage = "/main-og.png"
enableFreeTier = true 

[taxonomies]

[blog]
showSummary = true

[Permalinks]
post = "/:filename/"

[markup.goldmark.renderer]
unsafehtml = true
unsafe = true
hardWraps = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"
wrapStandAloneImageWithinParagraph = true
[markup.goldmark.parser.attribute]
block = true
title = true


[sitemap]
theme = "apitoolkit"

[author]
[author.anthony]
name = "Anthony Alaribe"
picture = "https://avatars.githubusercontent.com/u/6564482?v=4"
[author.irhose]
name = "Irhose Apori"
picture = "https://pbs.twimg.com/profile_images/1656791975088013312/W3q8KAJE_400x400.jpg"
[author.jessica]
name = "Jessica Ofem"
picture = "https://avatars.githubusercontent.com/u/42941436?v=4"
[author.dmytro]
name = "Dmytro Krasun"
picture = "https://pbs.twimg.com/profile_images/1678311781280759808/mDjAfPfC_400x400.jpg"
[author.collins]
name = "Collins Offiong"
picture = "https://avatars.githubusercontent.com/u/93836558?v=4"
[author.elliot]
name = "Elliot Brenya Sarfo"
picture = "https://avatars.githubusercontent.com/u/66503402?v=4"
[author.patrick]
name = "Patrick Odey"
picture = "https://avatars.githubusercontent.com/u/44481680?s=96&v=4"
